common:
  fp16: false
  log_format: json
  log_interval: 10
  all_gather_list_size: 2048000
  wandb_entity: ecg-pretraining
  wandb_project: question-answering

checkpoint:
  save_dir: checkpoints
  # best_checkpoint_metric: cinc_score
  maximize_best_checkpoint_metric: true
  save_interval: 1
  keep_last_epochs: 1
  save_interval_updates: 0
  no_epoch_checkpoints: false
  # patience: 30

task:
  _name: ecg_question_answering
  data: ???
  normalize: false
  enable_padding: true

dataset:
  num_workers: 6
  max_tokens: null 
  batch_size: 64
  valid_subset: "valid,test"

distributed_training:
  distributed_world_size: 1

criterion:
  _name: binary_cross_entropy_with_logits
  report_auc: true
  report_cinc_score: false
  weights_file: ???

optimization:
  max_epoch: 200
  max_update: 32000
  lr: [0.00005]

optimizer:
  _name: adam
  adam_betas: (0.9, 0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: qa_linear_projection
  num_labels: 165
  model_path: null
  no_pretrained_weights: true

  dropout: 0.0
  attention_dropout: 0.0
  activation_dropout: 0.1
  encoder_layerdrop: 0.1

  feature_grad_mult: 1.0
  freeze_finetune_updates: 0
  in_d: 12