
common:
  fp16: false
  log_format: json
  log_interval: 10
  all_gather_list_size: 2048000
  wandb_project: wav2vec2-finetuning

checkpoint:
  no_epoch_checkpoints: true
  best_checkpoint_metric: loss # auprc?
  patience: 50

task:
  _name: ecg_pretraining
  data: ???
  label: true
  normalize: false
  enable_padding: true

dataset:
  num_workers: 6
  max_tokens: null 
  batch_size: 128
  n_labels: 9
  valid_subset: "valid,test"

distributed_training:
  distributed_world_size: 8
  find_unused_parameters: true

criterion:
  _name: binary_cross_entropy_with_logits
  report_auc: true

optimization:
  max_epoch: 100
  lr: [5e-4]
  # update_freq: null

optimizer:
  _name: adam
  adam_betas: (0.9, 0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: fixed
  warmup_updates: 0

model:
  _name: wav2vec2_dc
  w2v_path: ???
  apply_mask: true
  mask_prob: 0.65
  mask_channel_prob: 0.5
  mask_channel_length: 64
  layerdrop: 0.1
  activation_dropout: 0.1
  feature_grad_mult: 0.0
  freeze_finetune_updates: 0
  no_pretrained_weights: false