
common:
  fp16: false
  log_format: json
  log_interval: 10
  all_gather_list_size: 2048000
  wandb_project: diagnosis-prediction

checkpoint:
  save_dir: checkpoints
  best_checkpoint_metric: cinc_score
  maximize_best_checkpoint_metric: true
  save_interval: 1
  keep_last_epochs: 1
  save_interval_updates: 0
  no_epoch_checkpoints: false
  patience: 30

task:
  _name: multi_label_classification
  num_labels: 26
  data: ???
  perturbation_mode: ['random_leads_masking']
  p: [1.0]
  mask_leads_selection: random
  mask_leads_prob: 0.75
  sample_rate: 125
  normalize: false
  enable_padding: true
  enable_padding_leads: false
  leads_to_load: "[0,1,2,3,4,5,7,10]"
  leads_bucket: null
    # I, II, III, aVR, aVL, aVF, V1, V2, V3, V4, V5, V6

dataset:
  num_workers: 6
  max_tokens: null 
  batch_size: 128
  valid_subset: "valid,test"

distributed_training:
  distributed_world_size: 1

criterion:
  _name: binary_cross_entropy_with_logits
  report_auc: true
  report_cinc_score: true
  weights_file: /home/jwoh/ecg/data/physionet2021/WFDB/weights.csv

optimization:
  max_epoch: 200
  max_update: 320000
  lr: [0.00005]

optimizer:
  _name: adam
  adam_betas: (0.9, 0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: fixed
  warmup_updates: 0

model:
  _name: linear_projection

  apply_mask: false
  mask_prob: 0.0

  dropout: 0.0
  attention_dropout: 0.0
  activation_dropout: 0.1

  feature_grad_mult: 1.0
  freeze_finetune_updates: 0
  in_d: 8