common:
  all_gather_list_size: 2048000
  wandb_entity: ecg-pretraining
  wandb_project: grounding-classification

common_eval:
  path: ???
  quiet: false
  model_overrides: "{'model_path': None, 'no_pretrained_weights': False}"

dataset:
  num_workers: 6
  max_tokens: null
  batch_size: 128
  valid_subset: "test_derived_per_lead_grounding,test_independent_per_lead_grounding"
  fixed_validation_seed: 1

task:
  _name: ecg_classification
  criterion_name: null
  data: ???
  path_dataset: true
  load_specific_lead: true
  enable_padding: true
  enable_padding_leads: true
  normalize: false

model: null