
common:
  fp16: false
  log_format: json
  log_interval: 1
  all_gather_list_size: 2048000

common_eval:
  path: ???
  model_overrides: "{'no_pretrained_weights': True, 'w2v_path': None, 'apply_mask': False}"

task:
  _name: ecg_identification
  data: ???
  label: true
  normalize: false
  enable_padding: true

dataset:
  max_tokens: null
  batch_size: 128
  valid_subset: "valid,test"

distributed_training:
  distributed_world_size: 1

criterion:
  _name: arcface
  # report_auc: true

model:
  _name: wav2vec2_id