common:
  fp16: false
  log_format: json
  log_interval: 10
  # wandb_project: clocs-pretraining

checkpoint:
  save_interval_updates: 250000
  keep_interval_updates: 1
  save_interval: 50
  no_epoch_checkpoints: false


task:
  _name: ecg_pretraining
  data: ???
  patient_dataset: true
  max_sample_size: 3000
  normalize: false

dataset:
  num_workers: 6
  max_tokens: null
  batch_size: 64
  valid_subset: ""
  disable_validation: true

distributed_training:
  distributed_world_size: 8

criterion:
  _name: clocs

optimization:
  max_epoch: 200
  lr: [5e-5]

optimizer:
  _name: adam
  adam_betas: (0.9, 0.98)
  adam_eps: 1e-06
  # weight_decay: 0.01

lr_scheduler:
  _name: fixed
  warmup_updates: 0

model:
  _name: clocs
  encoder_mode: transformer
  clocs_mode: cmsc # cmsc, cmlc, cmsmlc
  in_d: 1