common:
  fp16: false
  log_format: json
  log_interval: 50
  wandb_project: clocs-pretraining

checkpoint:
  save_interval: 50
  no_epoch_checkpoints: false
  

task:
  _name: ecg_pretraining
  clocs_mode: cmsc # cmsc, cmlc, cmsmlc
  data: ???
  patient_dataset: true
  max_sample_size: 3000
  normalize: false

dataset:
  num_workers: 6
  max_tokens: null
  batch_size: 256
  valid_subset: ""
  disable_validation: true

distributed_training:
  distributed_world_size: 1

criterion:
  _name: clocs

optimization:
  max_epoch: 400
  lr: [1e-4]

optimizer:
  _name: adam
  adam_betas: (0.9, 0.98)
  adam_eps: 1e-06
  # weight_decay: 0.01

lr_scheduler:
  _name: fixed
  warmup_updates: 0

model:
  _name: clocs
  encoder_mode: default
  in_d: 1