common:
  fp16: false
  log_format: json
  log_interval: 1
  all_gather_list_size: 2048000

common_eval:
  path: ???

task:
  _name: ecg_pretraining
  data: ???
  normalize: false
  enable_padding: true
  inferred_3kg_config:
    angle: 45
    scale: 1.5
    mask_ratio: 0.5

dataset:
  num_workers: 6
  max_tokens: null
  batch_size: 256
  valid_subset: "train"

distributed_training:
  distributed_world_size: 1

criterion:
  _name: 3kg

model:
  _name: 3kg