
common:
  fp16: false
  log_format: json
  log_interval: 1
  all_gather_list_size: 2048000

common_eval:
  path: ???
  model_overrides: "{'_name': 'arcface', 'no_pretrained_weights': True, 'apply_mask': False}"

task:
  _name: ecg_identification
  data: ???
  label: true
  normalize: false
  enable_padding: true
  enable_padding_leads: true
  leads_to_load: null
    # I, II, III, aVR, aVL, aVF, V1, V2, V3, V4, V5, V6


dataset:
  max_tokens: null 
  batch_size: 128
  valid_subset: "ptbxl"

distributed_training:
  distributed_world_size: 1

criterion:
  _name: arcface

model:
  _name: arcface
  no_pretrained_weights: true

  apply_mask: false
  mask_prob: 0.65
  mask_channel_prob: 0.5
  mask_channel_length: 64

  dropout: 0.0
  attention_dropout: 0.0
  activation_dropout: 0.1
  encoder_layerdrop: 0.1

  feature_grad_mult: 0.0
  freeze_finetune_updates: 0
  in_d: 12