common:
  fp16: false
  log_format: json
  log_interval: 10
  all_gather_list_size: 2048000
  wandb_entity: ecg-pretraining
  wandb_project: question-answering

checkpoint:
  save_dir: checkpoints
  best_checkpoint_metric: partial_accuracy
  maximize_best_checkpoint_metric: true
  save_interval: 1
  keep_last_epochs: 1
  save_interval_updates: 0
  no_epoch_checkpoints: false
  # patience: 30

task:
  _name: ecg_question_answering
  data: ???
  normalize: false
  enable_padding: true

dataset:
  num_workers: 6
  max_tokens: null
  batch_size: 8
  valid_subset: "valid,test"
  validate_interval: 1

distributed_training:
  distributed_world_size: 1

criterion:
  _name: binary_cross_entropy_with_logits
  report_auc: true
  multi_class_multi_label: true
  per_log_keys: [question_type1, question_type2, question_type3, template_id, attribute_id]

optimization:
  # max_epoch: 25
  max_update: 50000
  lr: [0.00005]
  update_freq: [8]

optimizer:
  _name: adam
  adam_betas: (0.9, 0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.4, 0.5]
  final_lr_scale: 0.05

model:
  _name: m3ae_qa
  num_labels: ???
  num_ecgs: 2
  model_path: ???
  no_pretrained_weights: false

  feature_grad_mult: 0.1
  freeze_finetune_updates: 0

  in_d: 12
  apply_mask: false