common:
  fp16: false
  log_format: json
  log_interval: 10
  all_gather_list_size: 2048000
  wandb_project: clocs-finetuning

checkpoint:
  best_checkpoint_metric: loss
  save_interval: 50
  no_epoch_checkpoints: false
  # patience: 20

task:
  _name: ecg_pretraining
  data: ???
  label: true
  patient_dataset: false
  enable_padding: true
  normalize: false

dataset:
  num_workers: 6
  max_tokens: null
  batch_size: 128
  n_labels: 26
  valid_subset: "valid,test"

distributed_training:
  distributed_world_size: 8

criterion:
  _name: binary_cross_entropy_with_logits
  report_auc: true
  report_score: true
  weights_file: ???

optimization:
  max_epoch: 250
  lr: [5e-4]

optimizer:
  _name: adam
  adam_betas: (0.9, 0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: fixed
  warmup_updates: 0

model:
  _name: clocs_dc
  clocs_path: ???
  in_d: 1
  freeze_finetune_updates: 0
  no_pretrained_weights: false