common:
  fp16: false
  log_format: json
  log_interval: 10
  all_gather_list_size: 2048000
  wandb_project: ecg-identification

checkpoint:
  save_dir: checkpoints
  best_checkpoint_metric: accuracy
  maximize_best_checkpoint_metric: True
  save_interval: 1
  keep_last_epochs: 1
  no_epoch_checkpoints: False
  patience: 30

task:
  _name: ecg_identification
  num_labels: 69978
  data: ???
  label: true
  normalize: false
  enable_padding: true

dataset:
  num_workers: 6
  max_tokens: null
  batch_size: 128
  valid_subset: "valid,test"
  disable_validation: false

distributed_training:
  distributed_world_size: 1

criterion:
  _name: arcface
  scale: 192
  margin: 1.0

optimization:
  max_epoch: 800
  max_update: 320000
  lr: [0.00003]

optimizer:
  _name: adam
  adam_betas: (0.9, 0.98)
  adam_eps: 1e-08

lr_scheduler:
  _name: tri_stage
  phase_ratio: [0.1, 0.2, 0.7]
  final_lr_scale: 0.01

model:
  _name: clocs_id
  clocs_path: ???
  freeze_finetune_updates: 0
  no_pretrained_weights: false
  in_d: 12

  dropout: 0.0
  feature_grad_mult: 0.0
  layerdrop: 0.1
  activation_dropout: 0.1